targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/pubspec_lock.dart
          - lib/src/package.dart
          - lib/src/package_description.dart
        options:
          any_map: true
          checked: true
          create_to_json: true
          explicit_to_json: true
          field_rename: snake