name: pubspec_lock_parse
version: 1.0.0
description: Simple package for parsing pubspec.lock files with a type-safe API and rich error reporting.
repository: https://github.com/matthewnitschke/pubspec_lock_parse

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  json_annotation: ^3.1.1
  pub_semver: ^1.4.4
  checked_yaml: ^1.0.4

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.5.1
  test: ^1.15.7
  stack_trace: ^1.9.2