name: pubspec_lock_parse
version: 2.0.1
description: Simple package for parsing pubspec.lock files with a type-safe API and rich error reporting.
repository: https://github.com/matthewnitschke/pubspec_lock_parse

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.3.0
  json_annotation: ^4.3.0
  pub_semver: ^2.1.0
  checked_yaml: ^2.0.1

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^6.0.1
  test: ^1.15.7
  stack_trace: ^1.9.2